export const thead = {
  Data: {
    HeaderRootId: "ROOT",
    Maxlevel: 1,
    Remark: null,
    Title: "数据时间分析",
    Headers: [
      [
        {
          Alignment: "Center",
          ColumnFormat: "String",
          ColumnIndex: 1,
          ColumnName: "RN",
          HeaderId: "XH1",
          HeaderIndex: 0,
          HeaderLevel: 0,
          HeaderName: "区县",
          Id: "XH1",
          IsFixed: false,
          LeafCount: 1,
          Level: 0,
          ParentId: "ROOT",
          Pid: "ROOT"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "总体情况",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 4,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "最近一次",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 4,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7, //横向位置
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "操作",
          Id: "M3_1",
          IsFixed: false,
          LeafCount: 1, //横向几列
          Level: 0, //
          ParentId: "M3",
          Pid: "M3"
        }
      ],
      [
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "开始同步日期",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "成功次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "失败次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步日期",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步状态",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步笔数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "错误描述",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        }
      ]
    ]
  }
};
