export const thead = {
  Data: {
    HeaderRootId: "ROOT",
    Maxlevel: 1,
    Remark: null,
    Title: "数据时间分析",
    Headers: [
      [
        {
          Alignment: "Center",
          ColumnFormat: "String",
          ColumnIndex: 1,
          ColumnName: "DISTRICTNAME",
          HeaderId: "XH1",
          HeaderIndex: 0,
          HeaderLevel: 0,
          HeaderName: "区县",
          Id: "XH1",
          IsFixed: false,
          LeafCount: 1,
          Level: 0,
          ParentId: "ROOT",
          Pid: "ROOT"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "总体情况",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 4,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "最近一次",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 4,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7, //横向位置
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "操作",
          Id: "M3_1",
          IsFixed: false,
          LeafCount: 1, //横向几列
          Level: 0, //
          ParentId: "M3",
          Pid: "M3"
        }
      ],
      [
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "开始同步日期",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "成功次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "失败次数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M1",
          Pid: "M1"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步日期",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步状态",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "同步笔数",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        },
        {
          Alignment: "Right",
          ColumnFormat: "N0S",
          ColumnIndex: 7,
          ColumnName: "M1_RS",
          HeaderId: "M1_1",
          HeaderIndex: 0,
          HeaderLevel: 1,
          HeaderName: "错误描述",
          Id: "M1_1",
          IsFixed: false,
          LeafCount: 1,
          Level: 1,
          ParentId: "M2",
          Pid: "M2"
        }
      ]
    ],
    Bdody: [
      {
        DISTRICTID: "500101",
        DISTRICTNAME: "万州区",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 99.0,
        FAIL: 1.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 867.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500106",
        DISTRICTNAME: "沙坪坝区",
        FIRSTDT: "2020-07-29",
        CT: 1.0,
        SUC: 0.0,
        FAIL: 1.0,
        LASTDT: "2020-07-29",
        STATUS: "异常",
        ROWCOUNT: null,
        REMARK: "未配置500106数据库!!!"
      },
      {
        DISTRICTID: "500114",
        DISTRICTNAME: "黔江区",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 99.0,
        FAIL: 1.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 10944.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500154",
        DISTRICTNAME: "开州区",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 99.0,
        FAIL: 1.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 276.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500156",
        DISTRICTNAME: "武隆区",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 97.0,
        FAIL: 3.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 2553.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500229",
        DISTRICTNAME: "城口县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 97.0,
        FAIL: 3.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 0.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500230",
        DISTRICTNAME: "丰都县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 99.0,
        FAIL: 1.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 8817.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500235",
        DISTRICTNAME: "云阳县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 90.0,
        FAIL: 10.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 29883.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500236",
        DISTRICTNAME: "奉节县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 89.0,
        FAIL: 11.0,
        LASTDT: "2020-07-23",
        STATUS: "异常",
        ROWCOUNT: null,
        REMARK: "错误"
      },
      {
        DISTRICTID: "500237",
        DISTRICTNAME: "巫山县",
        FIRSTDT: "2020-04-15",
        CT: 101.0,
        SUC: 100.0,
        FAIL: 1.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 0.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500238",
        DISTRICTNAME: "巫溪县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 100.0,
        FAIL: 0.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 82.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500240",
        DISTRICTNAME: "石柱土家族自治县",
        FIRSTDT: "2020-07-17",
        CT: 13.0,
        SUC: 10.0,
        FAIL: 3.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 0.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500242",
        DISTRICTNAME: "酉阳土家族苗族自治县",
        FIRSTDT: "2020-04-15",
        CT: 101.0,
        SUC: 89.0,
        FAIL: 12.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 604.0,
        REMARK: ""
      },
      {
        DISTRICTID: "500243",
        DISTRICTNAME: "彭水苗族土家族自治县",
        FIRSTDT: "2020-04-15",
        CT: 100.0,
        SUC: 94.0,
        FAIL: 6.0,
        LASTDT: "2020-07-23",
        STATUS: "正常",
        ROWCOUNT: 3195.0,
        REMARK: ""
      },
      {
        DISTRICTID: "汇总",
        DISTRICTNAME: "汇总",
        FIRSTDT: "2020-04-14",
        CT: 125.0,
        SUC: 0.0,
        FAIL: 125.0,
        LASTDT: "",
        STATUS: "警告",
        ROWCOUNT: null,
        REMARK: ""
      }
    ]
  }
};
