const a = {
  a: [
    [
      {
        rowSpan: "1",
        colSpan: "2",
        headerAlign: "center",
        isFixed: true,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "区县信息",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: "2",
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "年份",
        bodyCode: "YEAR",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: 1,
        colSpan: "3",
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "相关数据",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      }
    ],
    [
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "名称",
        bodyCode: "DISTRICTNAME",
        minWidth: "120",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "right",
        formatting: "String",
        headerName: "编码",
        minWidth: "100",
        bodyCode: "DISTRICTID",
        headerStyle: { textAlign: "center", minWidth: "100px" },
        bodyStyle: { textAlign: "right" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "right",
        formatting: "N0S",
        headerName: "人次（人次）",
        minWidth: "120",
        bodyCode: "RC",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: true,
        bodyAlign: "right",
        formatting: "N2S",
        headerName: "人数（人）",
        minWidth: "120",
        bodyCode: "RS",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" },
        path: "7lFmWiBZskOyIoShTmtAWQ",
        param: ["DISTRICTID"],
        location: { path: "7lFmWiBZskOyIoShTmtAWQ", param: ["DISTRICTID"] }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: true,
        bodyAlign: "right",
        formatting: "n2",
        headerName: "项目数（个）",
        minWidth: "120",
        bodyCode: "XMS",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" }
      }
    ]
  ],
  d: [
    [
      {
        rowSpan: "1",
        colSpan: "2",
        headerAlign: "center",
        isFixed: true,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "区县信息",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: "2",
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "年份",
        bodyCode: "YEAR",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: 1,
        colSpan: "3",
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "相关数据",
        headerStyle: { textAlign: "center", minWidth: "undefinedpx" },
        bodyStyle: { textAlign: "center" }
      }
    ],
    [
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "center",
        formatting: "String",
        headerName: "名称",
        bodyCode: "DISTRICTNAME",
        minWidth: "120",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "center" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "right",
        formatting: "String",
        headerName: "编码",
        minWidth: "100",
        bodyCode: "DISTRICTID",
        headerStyle: { textAlign: "center", minWidth: "100px" },
        bodyStyle: { textAlign: "right" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: false,
        bodyAlign: "right",
        formatting: "N0S",
        headerName: "人次（人次）",
        minWidth: "120",
        bodyCode: "RC",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: true,
        bodyAlign: "right",
        formatting: "N2S",
        headerName: "人数（人）",
        minWidth: "120",
        bodyCode: "RS",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" },
        path: "7lFmWiBZskOyIoShTmtAWQ",
        param: ["DISTRICTID"],
        location: { path: "7lFmWiBZskOyIoShTmtAWQ", param: ["DISTRICTID"] }
      },
      {
        rowSpan: 1,
        colSpan: 1,
        headerAlign: "center",
        isFixed: false,
        isSort: true,
        bodyAlign: "right",
        formatting: "n2",
        headerName: "项目数（个）",
        minWidth: "120",
        bodyCode: "XMS",
        headerStyle: { textAlign: "center", minWidth: "120px" },
        bodyStyle: { textAlign: "right" }
      }
    ]
  ],
  b: {
    Code: 1,
    Msg: "操作成功",
    ErrCode: null,
    ErrMsg: null,
    Data: [
      {
        Remark: "共24个项目,32534人次1,688.33万元",
        Bodys: {
          PageInfo: {
            PageIndex: 1,
            PageSize: 11,
            TotalPage: 3,
            TotalCount: 24
          },
          Items: [
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20002",
              CLASSNAME: "计划生育家庭特别扶助",
              PROJECTID: "500101wzXM05869",
              PROJECTNAME: "计划生育特别扶助家庭特别扶助金",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: null,
              M2_RC: null,
              M2_JE: "",
              M3_RS: null,
              M3_RC: null,
              M3_JE: "",
              M4_RS: 91.0,
              M4_RC: 91.0,
              M4_JE: "42.33",
              M5_RS: null,
              M5_RC: null,
              M5_JE: "",
              M6_RS: null,
              M6_RC: null,
              M6_JE: "",
              M7_RS: null,
              M7_RC: null,
              M7_JE: "",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 1.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20002",
              CLASSNAME: "计划生育家庭特别扶助",
              PROJECTID: "500101wzXM06109",
              PROJECTNAME: "计划生育手术并发症扶助",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: null,
              M2_RC: null,
              M2_JE: "",
              M3_RS: null,
              M3_RC: null,
              M3_JE: "",
              M4_RS: 4.0,
              M4_RC: 4.0,
              M4_JE: "0.96",
              M5_RS: null,
              M5_RC: null,
              M5_JE: "",
              M6_RS: null,
              M6_RC: null,
              M6_JE: "",
              M7_RS: null,
              M7_RC: null,
              M7_JE: "",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 2.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101wzXM05816",
              PROJECTNAME: "高龄老人长寿补贴金",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: null,
              M2_RC: null,
              M2_JE: "",
              M3_RS: null,
              M3_RC: null,
              M3_JE: "",
              M4_RS: null,
              M4_RC: null,
              M4_JE: "",
              M5_RS: 144.0,
              M5_RC: 144.0,
              M5_JE: "7.79",
              M6_RS: null,
              M6_RC: null,
              M6_JE: "",
              M7_RS: null,
              M7_RC: null,
              M7_JE: "",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 3.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101wzXM05818",
              PROJECTNAME: "特困供养",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: 357.0,
              M1_RC: 357.0,
              M1_JE: "28.00",
              M2_RS: 356.0,
              M2_RC: 356.0,
              M2_JE: "27.95",
              M3_RS: 353.0,
              M3_RC: 353.0,
              M3_JE: "27.73",
              M4_RS: 349.0,
              M4_RC: 349.0,
              M4_JE: "27.42",
              M5_RS: 349.0,
              M5_RC: 349.0,
              M5_JE: "27.48",
              M6_RS: 349.0,
              M6_RC: 349.0,
              M6_JE: "27.49",
              M7_RS: 347.0,
              M7_RC: 347.0,
              M7_JE: "27.39",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 4.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101wzXM05820",
              PROJECTNAME: "经济困难的失能老年人养老服务补贴",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: null,
              M2_RC: null,
              M2_JE: "",
              M3_RS: 26.0,
              M3_RC: 26.0,
              M3_JE: "1.56",
              M4_RS: null,
              M4_RC: null,
              M4_JE: "",
              M5_RS: null,
              M5_RC: null,
              M5_JE: "",
              M6_RS: 33.0,
              M6_RC: 33.0,
              M6_JE: "1.66",
              M7_RS: null,
              M7_RC: null,
              M7_JE: "",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 5.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101wzXM05822",
              PROJECTNAME: "孤儿基本生活费",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: 6.0,
              M1_RC: 6.0,
              M1_JE: "0.72",
              M2_RS: 6.0,
              M2_RC: 6.0,
              M2_JE: "0.72",
              M3_RS: 6.0,
              M3_RC: 6.0,
              M3_JE: "0.72",
              M4_RS: 6.0,
              M4_RC: 6.0,
              M4_JE: "0.72",
              M5_RS: 6.0,
              M5_RC: 6.0,
              M5_JE: "0.72",
              M6_RS: 6.0,
              M6_RC: 6.0,
              M6_JE: "0.72",
              M7_RS: 6.0,
              M7_RC: 6.0,
              M7_JE: "0.72",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 6.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101wzXM05966",
              PROJECTNAME: "经济困难的高龄老年人养老服务补贴",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: null,
              M2_RC: null,
              M2_JE: "",
              M3_RS: 70.0,
              M3_RC: 70.0,
              M3_JE: "4.20",
              M4_RS: null,
              M4_RC: null,
              M4_JE: "",
              M5_RS: null,
              M5_RC: null,
              M5_JE: "",
              M6_RS: null,
              M6_RC: null,
              M6_JE: "",
              M7_RS: 95.0,
              M7_RC: 95.0,
              M7_JE: "4.70",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 7.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101b60aa8d2-4da3-4993-8558-be18ddf84b5f",
              PROJECTNAME: "农村最低生活保障",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: 1080.0,
              M1_RC: 1080.0,
              M1_JE: "38.67",
              M2_RS: 1087.0,
              M2_RC: 1087.0,
              M2_JE: "38.89",
              M3_RS: 1078.0,
              M3_RC: 1078.0,
              M3_JE: "38.50",
              M4_RS: 1078.0,
              M4_RC: 1078.0,
              M4_JE: "38.50",
              M5_RS: 1078.0,
              M5_RC: 1078.0,
              M5_JE: "38.56",
              M6_RS: 1110.0,
              M6_RC: 1110.0,
              M6_JE: "39.66",
              M7_RS: 1132.0,
              M7_RC: 1132.0,
              M7_JE: "40.55",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 8.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20003",
              CLASSNAME: "困难群众救助补助",
              PROJECTID: "500101bb2599b5-045c-4aef-8bbf-76ba65cbbeff",
              PROJECTNAME: "城市最低生活保障",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: 498.0,
              M1_RC: 498.0,
              M1_JE: "21.58",
              M2_RS: 495.0,
              M2_RC: 495.0,
              M2_JE: "21.49",
              M3_RS: 493.0,
              M3_RC: 493.0,
              M3_JE: "21.38",
              M4_RS: 491.0,
              M4_RC: 491.0,
              M4_JE: "21.27",
              M5_RS: 497.0,
              M5_RC: 497.0,
              M5_JE: "21.47",
              M6_RS: 504.0,
              M6_RC: 504.0,
              M6_JE: "21.77",
              M7_RS: 513.0,
              M7_RC: 513.0,
              M7_JE: "22.14",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 9.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20004",
              CLASSNAME: "困难群众临时救助",
              PROJECTID: "500101wzXM05808",
              PROJECTNAME: "城乡困难群众临时救助",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: null,
              M1_RC: null,
              M1_JE: "",
              M2_RS: 7.0,
              M2_RC: 7.0,
              M2_JE: "6.44",
              M3_RS: null,
              M3_RC: null,
              M3_JE: "",
              M4_RS: null,
              M4_RC: null,
              M4_JE: "",
              M5_RS: null,
              M5_RC: null,
              M5_JE: "",
              M6_RS: 8.0,
              M6_RC: 8.0,
              M6_JE: "7.57",
              M7_RS: 6.0,
              M7_RC: 6.0,
              M7_JE: "5.07",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 10.0
            },
            {
              HIGHID: "L11",
              HIGHNAME: "“两不愁”",
              CLASSID: "L20005",
              CLASSNAME: "重度残疾人护理补贴 ",
              PROJECTID: "500101wzXM05921",
              PROJECTNAME: "残疾人护理补贴",
              DISTRICTID: "500101",
              DISTRICTNAME: "万州区",
              COUNTRYID: "500101151",
              COUNTRYNAME: "龙驹镇",
              YEAR: "2020",
              M1_RS: 411.0,
              M1_RC: 411.0,
              M1_JE: "3.03",
              M2_RS: 410.0,
              M2_RC: 410.0,
              M2_JE: "2.98",
              M3_RS: 400.0,
              M3_RC: 400.0,
              M3_JE: "2.91",
              M4_RS: 400.0,
              M4_RC: 400.0,
              M4_JE: "2.91",
              M5_RS: 425.0,
              M5_RC: 425.0,
              M5_JE: "3.26",
              M6_RS: 421.0,
              M6_RC: 421.0,
              M6_JE: "3.05",
              M7_RS: null,
              M7_RC: null,
              M7_JE: "",
              M8_RS: null,
              M8_RC: null,
              M8_JE: "",
              M9_RS: null,
              M9_RC: null,
              M9_JE: "",
              M10_RS: null,
              M10_RC: null,
              M10_JE: "",
              M11_RS: null,
              M11_RC: null,
              M11_JE: "",
              M12_RS: null,
              M12_RC: null,
              M12_JE: "",
              RN: 11.0
            }
          ],
          Total: null
        }
      }
    ]
  }
};
